### ISSUE TITLE
[META] Follow advance

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/engineering-shiny-book#105]
Meta issue to follow the advance of the writing:

+ [ ] Introduction
+ [x] Motivation
+ [x] Book structure
+ [ ] About the authors
+ [x] Want to help?
+ [ ] Other resources
+ [ ] Acknowledgments
+ [x] I Building Successful Shiny Apps
+ [x] 1 About Successful Shiny Apps
+ [x] 1.1 A (very) short introduction to Shiny
+ [x] 1.2 What’s a complex Shiny App?
+ [x] 1.3 What’s a successful Shiny App?
+ [x] 2 Planning Ahead
+ [x] 2.1 Working with a “long-term” mindset
+ [x] 2.2 Working as a team: tools & organisation
+ [x] 3 Structuring your Project
+ [x] 3.1 Shiny App as a Package
+ [x] 3.2 Using Shiny Modules
+ [x] 3.3 Splitting your app into files
+ [x] 4 Introduction to {golem}
+ [x] 4.1 Getting started with {golem}
+ [x] 4.2 Understanding {golem} app structure
+ [x] 5 The workflow
+ [x] 5.1 Part 1: Design
+ [x] 5.2 Part 2: Prototype
+ [x] 5.3 Part 3: Build
+ [x] 5.4 Part 4: Secure
+ [x] 5.5 Part 5: Deploy
+ [x] II Step 1: Designing
+ [x] 6 UX Matters
+ [x] 6.1 Simplicity is Gold
+ [x] 6.2 The danger of feature-creep
+ [x] 6.3 About Accessibility
+ [x] 7 Don’t rush into coding
+ [x] 7.1 Designing before coding
+ [x] 7.2 Ask questions
+ [x] 8 A Gentle Introduction to CSS
+ [x] 8.1 What is CSS
+ [x] 8.2 Getting started with CSS
+ [x] 8.3 Integrate CSS files to your Shiny App
+ [x] III Step 2: Prototype
+ [x] 9 Building an “ipsum-app”
+ [x] 9.1 Prototyping is crucial
+ [x] 9.2 The “UI first” approach
+ [x] 10 Building with RMarkdown
+ [x] 10.1 Define the content of the application
+ [x] 10.2 Fill the Rmd files
+ [x] 10.3 Use the ‘Rmd first’ method to document further
+ [x] 11 Tools for prototyping
+ [x] 11.1 Fast prototyping with {shinipsum}
+ [x] 11.2 Using {fakir} for fake data generation
+ [x] IV Step 3: Build
+ [x] 12 Building app with {golem}
+ [x] 12.1 Using {golem}
+ [x] 12.2 dev/01_start.R
+ [x] 12.3 Day to Day Dev with {golem}
+ [x] 12.4 Launching the app
+ [x] 12.5 dev/02_dev.R
+ [x] 12.6 Adding these external resources to your app
+ [x] 12.7 Documentation
+ [x] 12.8 Using {golem} dev functions
+ [x] V Step 4: Secure
+ [x] 13 Build yourself a safety net
+ [x] 13.1 Testing your app
+ [x] 13.2 A reproducible environment
+ [x] 14 Secure your work
+ [x] 14.1 Using Version Control with git
+ [x] 14.2 Git integration
+ [x] 14.3 CI and testing
+ [x] VI Step 5: Deploy
+ [x] 15 Send your app to production
+ [x] 15.1 Where to deploy your app
+ [x] 15.2 Before deployment Check-list
+ [x] 16 Deploy with {golem}
+ [x] 16.1 Local deployment
+ [x] 16.2 Deploying Apps with {golem}
+ [x] 16.3 RStudio Environments
+ [x] 16.4 Docker
+ [x] VII Optimizing
+ [x] 17 The Need for Optimization
+ [x] 17.1 Build first, then optimize
+ [x] 17.2 Tools for profiling
+ [x] 18 Common Application Caveats
+ [x] 18.1 Reactivity anti-patterns
+ [x] 18.2 R does too much
+ [x] 19 Optimizing Shiny Code
+ [x] 19.1 Reading data
+ [x] 19.2 Caching elements
+ [x] 20 Using JavaScript
+ [x] 20.1 A quick introduction to JavaScript
+ [x] 20.2 Client-side JavaScript
+ [x] 20.3 JavaScript <-> Shiny communication
+ [x] 20.4 About {golem} js functions
+ [x] 20.5 Learn more about JavaScript

**Comment by statnmap** [comment]
Follow the advance of the review

+ [ ] Introduction
+ [ ] Motivation
+ [ ] Book structure
+ [ ] About the authors
+ [ ] Want to help?
+ [ ] Other resources
+ [ ] Acknowledgments
+ [x] I Building Successful Shiny Apps
+ [x] 1 About Successful Shiny Apps
+ [x] 1.1 A (very) short introduction to Shiny
+ [x] 1.2 What’s a complex Shiny App?
+ [x] 1.3 What’s a successful Shiny App?
+ [x] 2 Planning Ahead
+ [x] 2.1 Working with a “long-term” mindset
+ [x] 2.2 Working as a team: tools & organisation
+ [ ] 3 Structuring your Project
+ [x] 3.1 Shiny App as a Package
+ [ ] 3.2 Using Shiny Modules
+ [ ] 3.3 Splitting your app into files
+ [ ] 4 Introduction to {golem}
+ [ ] 4.1 Getting started with {golem}
+ [ ] 4.2 Understanding {golem} app structure
+ [ ] 5 The workflow
+ [ ] 5.1 Part 1: Design
+ [ ] 5.2 Part 2: Prototype
+ [ ] 5.3 Part 3: Build
+ [ ] 5.4 Part 4: Secure
+ [ ] 5.5 Part 5: Deploy
+ [ ] II Step 1: Designing
+ [ ] 6 UX Matters
+ [ ] 6.1 Simplicity is Gold
+ [ ] 6.2 The danger of feature-creep
+ [ ] 6.3 About Accessibility
+ [ ] 7 Don’t rush into coding
+ [ ] 7.1 Designing before coding
+ [ ] 7.2 Ask questions
+ [ ] 8 A Gentle Introduction to CSS
+ [ ] 8.1 What is CSS
+ [ ] 8.2 Getting started with CSS
+ [ ] 8.3 Integrate CSS files to your Shiny App
+ [ ] III Step 2: Prototype
+ [ ] 9 Building an “ipsum-app”
+ [ ] 9.1 Prototyping is crucial
+ [ ] 9.2 The “UI first” approach
+ [ ] 10 Building with RMarkdown
+ [ ] 10.1 Define the content of the application
+ [ ] 10.2 Fill the Rmd files
+ [ ] 10.3 Use the ‘Rmd first’ method to document further
+ [ ] 11 Tools for prototyping
+ [ ] 11.1 Fast prototyping with {shinipsum}
+ [ ] 11.2 Using {fakir} for fake data generation
+ [ ] IV Step 3: Build
+ [ ] 12 Building app with {golem}
+ [ ] 12.1 Using {golem}
+ [ ] 12.2 dev/01_start.R
+ [ ] 12.3 Day to Day Dev with {golem}
+ [ ] 12.4 Launching the app
+ [ ] 12.5 dev/02_dev.R
+ [ ] 12.6 Adding these external resources to your app
+ [ ] 12.7 Documentation
+ [ ] 12.8 Using {golem} dev functions
+ [ ] V Step 4: Secure
+ [ ] 13 Build yourself a safety net
+ [ ] 13.1 Testing your app
+ [ ] 13.2 A reproducible environment
+ [ ] 14 Secure your work
+ [ ] 14.1 Using Version Control with git
+ [ ] 14.2 Git integration
+ [ ] 14.3 CI and testing
+ [ ] VI Step 5: Deploy
+ [ ] 15 Send your app to production
+ [ ] 15.1 Where to deploy your app
+ [ ] 15.2 Before deployment Check-list
+ [ ] 16 Deploy with {golem}
+ [ ] 16.1 Local deployment
+ [ ] 16.2 Deploying Apps with {golem}
+ [ ] 16.3 RStudio Environments
+ [ ] 16.4 Docker
+ [ ] VII Optimizing
+ [ ] 17 The Need for Optimization
+ [ ] 17.1 Build first, then optimize
+ [ ] 17.2 Tools for profiling
+ [ ] 18 Common Application Caveats
+ [ ] 18.1 Reactivity anti-patterns
+ [ ] 18.2 R does too much
+ [ ] 19 Optimizing Shiny Code
+ [ ] 19.1 Reading data
+ [ ] 19.2 Caching elements
+ [ ] 20 Using JavaScript
+ [ ] 20.1 A quick introduction to JavaScript
+ [ ] 20.2 Client-side JavaScript
+ [ ] 20.3 JavaScript <-> Shiny communication
+ [ ] 20.4 About {golem} js functions
+ [ ] 20.5 Learn more about JavaScript

**Comment by statnmap** [comment]
Review images captions
- [ ] 01-big-shiny
